using System.Text;
using EnananBot.Modules.Base;
using EnananBot.Services;
using EnananBot.Utils;
using NetCord;
using NetCord.Services.ApplicationCommands;

// ReSharper disable NullableWarningSuppressionIsUsed
// ReSharper disable UnusedType.Global
// ReSharper disable UnusedMember.Global

namespace EnananBot.Modules.Commands;

/// <summary>
/// Slash Command Module for Color Utilities.
/// Base Command: /color
/// Contains tools for visualizing colors and generating palettes.
/// </summary>
[SlashCommand("color", "Commands related to role colors, previews, and palettes.")]
public class ColorCommands(
    HttpClient http,
    ValidationService validationService,
    ImageGeneratorService imageGenerator,
    MessageService messages)
    : RegisteredGuildModule(validationService) // Inherits the "EnsureGuildRegisteredAsync" check
{
    // Local reference to the validation service passed to the base class
    private readonly ValidationService _validationService = validationService;

    /// <summary>
    /// Command: /color preview [color]
    /// Generates a fake "Discord Chat Message" image showing how the user's name would look with the specific color.
    /// </summary>
    [SubSlashCommand("preview", "Want a quick mockup? I'll show you how things look with your new colors.")]
    public async Task PreviewColor(
        [SlashCommandParameter(Name = "color", Description = "Can be a hex code or a color name!", MinLength = 3)]
        string colorString)
    {
        // Is the server in our database?
        if (!await EnsureGuildRegisteredAsync())
            return;

        // Image generation takes time
        // This tells Discord "I'm thinking..." so the token doesn't expire
        await ResponseUtils.DeferAsync(Context);

        var user = (GuildUser)Context.User;
        var username = user.Nickname ?? user.GlobalName ?? user.Username;
        
        try
        {
            // Clean and check the color string
            var roleColorInput = colorString.ToLowerInvariant().StripInvalidChars();
            if (!await TryValidateAsync(_validationService.ValidateRequiredColor(roleColorInput, username)))
                return;

            var roleColor = ColorUtils.GetNormalizedHex(roleColorInput);

            // Fetch User Avatar needed for the mock-up image
            var avatarUrl = (user.GetGuildAvatarUrl(ImageFormat.Png)
                             ?? user.GetAvatarUrl(ImageFormat.Png)
                             ?? user.DefaultAvatarUrl) + "?size=256";

            // Download the avatar bytes
            var avatarBytes = await http.GetByteArrayAsync(avatarUrl);

            // Uses ImageGeneratorService to draw the preview
            var renderBytes =
                imageGenerator.GenerateNamePreview(username, roleColor, avatarBytes);

            // Send the generated bytes as a file attachment
            using var stream = new MemoryStream(renderBytes);

            await ResponseUtils.SendImageResponse(
                Context,
                messages.MessagePreviewSuccess(username),
                stream);
        }
        catch (Exception e)
        {
            Console.WriteLine("Error generating preview image: " + e.Message);
            
            await ResponseUtils.SendSimpleResponse(
                Context,
                messages.MessagePreviewError(username),
                true);
        }
        finally
        {
            // Cleanup interaction state
            ResponseUtils.Clear(Context);
        }
    }

    /// <summary>
    /// Command: /color palette [color]
    /// Generates a gradient strip based on the input color. Useful for finding matching themes.
    /// </summary>
    [SubSlashCommand("palette", "Looking for inspiration? I can generate a color palette for you.")]
    public async Task GeneratePalette(
        [SlashCommandParameter(
            Name = "color",
            Description = "An already existing named color for you to grab some inspiration!",
            AutocompleteProviderType = typeof(AutocompleteService.NamedColorsProvider))]
        string namedColor)
    {
        if (!await EnsureGuildRegisteredAsync()) return;

        await ResponseUtils.DeferAsync(Context);

        var user = (GuildUser)Context.User;
        var username = user.Nickname ?? user.GlobalName ?? user.Username;
        
        try
        {
            // Validate Input
            var roleColor = namedColor.ToLowerInvariant().StripInvalidChars();
            if (!await TryValidateAsync(_validationService.ValidateRequiredColor(roleColor, username)))
                return;
            
            // Generate Palette
            var colors = ColorUtils.GetPalette(roleColor);
            
            // Draw Palette Image
            var paletteBytes = imageGenerator.GeneratePaletteImage(colors);

            using var stream = new MemoryStream(paletteBytes);

            // Format the text description (List of Hex codes)
            var description = new StringBuilder()
                .AppendLine(messages.ColorPaletteSuccess(username))
                .AppendLine()
                .AppendLine(colors.PrettifyArray())
                .ToString();

            // Send Image + Text
            await ResponseUtils.SendImageResponse(
                Context,
                description,
                stream);
        }
        catch (Exception e)
        {
            Console.WriteLine("Error generating color palette: " + e.Message);
            
            await ResponseUtils.SendSimpleResponse(
                Context,
                messages.ColorPaletteError(),
                true);
        }
        finally
        {
            ResponseUtils.Clear(Context);
        }
    }

    /// <summary>
    /// Command: /color list
    /// Provides a link to the web palette list (since listing 148 colors is just too many)
    /// </summary>
    [SubSlashCommand("list", "I'm not listing every color by hand, but I can show you where they all are.")]
    public async Task ListAllColors()
    {
        if (!await EnsureGuildRegisteredAsync()) return;

        var user = (GuildUser)Context.User;
        var username = user.Nickname ?? user.GlobalName ?? user.Username;

        try
        {
            await ResponseUtils.SendSimpleResponse(
                Context,
                messages.ListAllColors(username, "https://enanan.soaringpromise.moe/palette"));
        }
        catch (Exception e)
        {
            Console.WriteLine("Error sending color list: " + e.Message);
        }
    }
}